"""Initial migration

Revision ID: 0dae75d4309b
Revises: 
Create Date: 2025-06-27 18:55:28.077513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0dae75d4309b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.AutoString(), nullable=False),
    sa.Column('innohassle_id', sqlmodel.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False),
    sa.Column('email', sqlmodel.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshops',
    sa.Column('id', sqlmodel.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.AutoString(), nullable=True),
    sa.Column('dtstart', sa.DateTime(), nullable=False),
    sa.Column('dtend', sa.DateTime(), nullable=False),
    sa.Column('place', sqlmodel.AutoString(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('remain_places', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_registrable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workshops_id'), 'workshops', ['id'], unique=False)
    op.create_index(op.f('ix_workshops_name'), 'workshops', ['name'], unique=False)
    op.create_table('workshopcheckin',
    sa.Column('user_id', sqlmodel.AutoString(), nullable=False, on_delete='CASCADE'),
    sa.Column('workshop_id', sqlmodel.AutoString(), nullable=False, on_delete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'workshop_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workshopcheckin')
    op.drop_index(op.f('ix_workshops_name'), table_name='workshops')
    op.drop_index(op.f('ix_workshops_id'), table_name='workshops')
    op.drop_table('workshops')
    op.drop_table('users')
    # ### end Alembic commands ###
