"""make enum names uppercase

Revision ID: 17e3c4626f87
Revises: d17584e7d616
Create Date: 2025-12-10 19:13:04.268802

"""

from collections.abc import Sequence

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17e3c4626f87"
down_revision: str | None = "d17584e7d616"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="userrole",
        new_values=["ADMIN", "USER"],
        affected_columns=[TableReference(table_schema="public", table_name="users", column_name="role")],
        enum_values_to_rename=[("admin", "ADMIN"), ("user", "USER")],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="workshoplanguage",
        new_values=["ENGLISH", "RUSSIAN", "BOTH"],
        affected_columns=[TableReference(table_schema="public", table_name="workshops", column_name="language")],
        enum_values_to_rename=[("english", "ENGLISH"), ("russian", "RUSSIAN"), ("both", "BOTH")],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="checkintype",
        new_values=["NO_CHECK_IN", "ON_INNOHASSLE", "BY_LINK"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="workshops",
                column_name="check_in_type",
                existing_server_default="'on_innohassle'::checkintype",
            )
        ],
        enum_values_to_rename=[
            ("no_checkin", "NO_CHECK_IN"),
            ("on_innohassle", "ON_INNOHASSLE"),
            ("by_link", "BY_LINK"),
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="checkintype",
        new_values=["no_checkin", "on_innohassle", "by_link"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="workshops",
                column_name="check_in_type",
                existing_server_default="'on_innohassle'::checkintype",
            )
        ],
        enum_values_to_rename=[
            ("NO_CHECK_IN", "no_checkin"),
            ("ON_INNOHASSLE", "on_innohassle"),
            ("BY_LINK", "by_link"),
        ],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="workshoplanguage",
        new_values=["english", "russian", "both"],
        affected_columns=[TableReference(table_schema="public", table_name="workshops", column_name="language")],
        enum_values_to_rename=[("ENGLISH", "english"), ("RUSSIAN", "russian"), ("BOTH", "both")],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="userrole",
        new_values=["admin", "user"],
        affected_columns=[TableReference(table_schema="public", table_name="users", column_name="role")],
        enum_values_to_rename=[("ADMIN", "admin"), ("USER", "user")],
    )
    # ### end Alembic commands ###
