"""add both to languages selector

Revision ID: 49e8a11e1ab2
Revises: fb4c5dca7e15
Create Date: 2025-11-06 23:50:51.757591

"""

from collections.abc import Sequence

from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49e8a11e1ab2"
down_revision: str | None = "fb4c5dca7e15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="workshoplanguage",
        new_values=["english", "russian", "both"],
        affected_columns=[TableReference(table_schema="public", table_name="workshops", column_name="language")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="workshoplanguage",
        new_values=["english", "russian"],
        affected_columns=[TableReference(table_schema="public", table_name="workshops", column_name="language")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
