"""remove is registrable field

Revision ID: 8e57f5672a01
Revises: f9f2b604a9d9
Create Date: 2025-08-15 21:20:22.651902

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e57f5672a01"
down_revision: str | None = "f9f2b604a9d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workshops", "is_registrable")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workshops", sa.Column("is_registrable", sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
