"""add check-in type enum and check-in link

Revision ID: d17584e7d616
Revises: 169f3080b782
Create Date: 2025-12-10 03:05:48.611423

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d17584e7d616"
down_revision: str | None = "169f3080b782"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("no_checkin", "on_innohassle", "by_link", name="checkintype").create(op.get_bind())
    op.add_column(
        "workshops",
        sa.Column(
            "check_in_type",
            postgresql.ENUM("no_checkin", "on_innohassle", "by_link", name="checkintype", create_type=False),
            server_default="on_innohassle",
            nullable=False,
        ),
    )
    op.add_column("workshops", sa.Column("check_in_link", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workshops", "check_in_link")
    op.drop_column("workshops", "check_in_type")
    sa.Enum("no_checkin", "on_innohassle", "by_link", name="checkintype").drop(op.get_bind())
    # ### end Alembic commands ###
