"""separate title/desc by languages, add badges, check-in open time, host

Revision ID: fb4c5dca7e15
Revises: 8e57f5672a01
Create Date: 2025-11-06 04:11:59.402482

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb4c5dca7e15"
down_revision: str | None = "8e57f5672a01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("english", "russian", name="workshoplanguage").create(op.get_bind())
    op.add_column("workshops", sa.Column("english_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column("workshops", sa.Column("russian_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column("workshops", sa.Column("english_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("workshops", sa.Column("russian_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column(
        "workshops",
        sa.Column(
            "language",
            postgresql.ENUM("english", "russian", name="workshoplanguage", create_type=False),
            nullable=False,
        ),
    )
    op.add_column("workshops", sa.Column("host", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column("workshops", sa.Column("check_in_opens", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "workshops",
        sa.Column(
            "badges", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
    )
    op.add_column("workshops", sa.Column("is_draft", sa.Boolean(), nullable=False))
    op.drop_index(op.f("ix_workshops_name"), table_name="workshops")
    op.create_index(op.f("ix_workshops_english_name"), "workshops", ["english_name"], unique=False)
    op.create_index(op.f("ix_workshops_russian_name"), "workshops", ["russian_name"], unique=False)
    op.drop_column("workshops", "description")
    op.drop_column("workshops", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workshops", sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column("workshops", sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f("ix_workshops_russian_name"), table_name="workshops")
    op.drop_index(op.f("ix_workshops_english_name"), table_name="workshops")
    op.create_index(op.f("ix_workshops_name"), "workshops", ["name"], unique=False)
    op.drop_column("workshops", "is_draft")
    op.drop_column("workshops", "badges")
    op.drop_column("workshops", "check_in_opens")
    op.drop_column("workshops", "host")
    op.drop_column("workshops", "language")
    op.drop_column("workshops", "russian_description")
    op.drop_column("workshops", "english_description")
    op.drop_column("workshops", "russian_name")
    op.drop_column("workshops", "english_name")
    sa.Enum("english", "russian", name="workshoplanguage").drop(op.get_bind())
    # ### end Alembic commands ###
