"""add check_in_closes field

Revision ID: 20dcf337bb3e
Revises: 55b046067d40
Create Date: 2026-02-13 21:38:00.204684

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20dcf337bb3e"
down_revision: str | None = "55b046067d40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workshops", sa.Column("check_in_closes", sa.DateTime(timezone=True), nullable=True))
    op.execute(
        """
        UPDATE workshops
        SET check_in_closes = dtstart
        WHERE dtend IS NOT NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workshops", "check_in_closes")
    # ### end Alembic commands ###
