"""remove db side null checks to support drafts

Revision ID: f0503791c7b6
Revises: 49e8a11e1ab2
Create Date: 2025-11-20 21:39:53.148557

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0503791c7b6"
down_revision: str | None = "49e8a11e1ab2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workshops",
        "language",
        existing_type=postgresql.ENUM("english", "russian", "both", name="workshoplanguage"),
        nullable=True,
    )
    op.alter_column("workshops", "host", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("workshops", "capacity", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("UPDATE workshops SET host = '' WHERE host IS NULL")
    op.execute("UPDATE workshops SET capacity = 1000000 WHERE capacity IS NULL")
    op.execute("UPDATE workshops SET language = 'both' WHERE language IS NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("workshops", "capacity", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("workshops", "host", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "workshops",
        "language",
        existing_type=postgresql.ENUM("english", "russian", "both", name="workshoplanguage"),
        nullable=False,
    )
    # ### end Alembic commands ###
