"""add image file id field for minio

Revision ID: 169f3080b782
Revises: bfc04b979ad6
Create Date: 2025-11-21 00:01:12.659550

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "169f3080b782"
down_revision: str | None = "bfc04b979ad6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workshops", sa.Column("image_file_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workshops", "image_file_id")
    # ### end Alembic commands ###
