"""remain places

Revision ID: f9f2b604a9d9
Revises: 045ff0ee663b
Create Date: 2025-08-11 22:25:51.102520

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9f2b604a9d9"
down_revision: str | None = "045ff0ee663b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("workshops", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("workshops", "is_registrable", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_column("workshops", "remain_places")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workshops", sa.Column("remain_places", sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column("workshops", "is_registrable", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("workshops", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
