"""New field in User

Revision ID: af0b8cd0841b
Revises: 0dae75d4309b
Create Date: 2025-07-10 16:50:17.502149

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "af0b8cd0841b"
down_revision: Union[str, None] = "0dae75d4309b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("t_alias", sqlmodel.AutoString()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "t_alias")
    # ### end Alembic commands ###
