name: Deploy FastAPI on Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd ${{ secrets.BACKEND_REPO_PATH }}
          git stash
          git pull origin main
          source venv/bin/activate
          uv pip install -r .
          sudo systemctl restart backend.service